import { ServiceItem } from "../utilities/types/types";
import { v4 as uuid } from "uuid";
export const servicesData: ServiceItem[] = [
  {
    subType: "markets",
    id: uuid(),
    itemType: "service-item",
    orderIdx: 0,
    timestamp: Date.now(),
    pk: {
      itemType: "service-item",
      orderIdx: 0,
    },
    images: {
      [uuid()]: {
        pk: {
          itemType: "service-item",
          orderIdx: 0,
        },
        id: uuid(),
        timestamp: Date.now(),
        imgUrl: "",
        placeholderUrl: "",
        description: "",
        orderIdx: 0,
      },
    },
    subCategories: [
      "Residential Design",
      "Retail Design",
      "Restaurant Design",
      "Hospitality Design ",
      "Workplace Design",
      "Pop-Up Experiences",
      "Shop-In-Shop’s",
      "Sports & Entertainment Venues",
      "Multifamily Developments",
      "Senior / Student Living",
      "Experience Adaptations",
      "Landscape / Gardens Design",
      "Mixed-Use",
      "Multifamily Residential",
      "Art Galleries",
      "Venues",
    ],
  },
  {
    subType: "architecture-interior",
    id: uuid(),
    itemType: "service-item",
    orderIdx: 1,
    timestamp: Date.now(),
    pk: {
      itemType: "service-item",
      orderIdx: 1,
    },
    images: {
      [uuid()]: {
        pk: {
          itemType: "service-item",
          orderIdx: 0,
        },
        id: uuid(),
        timestamp: Date.now(),
        imgUrl: "",
        placeholderUrl: "",
        description: "",
        orderIdx: 0,
      },
    },
    subCategories: [
      "Project planning",
      "Floor Plans",
      "Concept development",
      "Color & Material Selection",
      "Options Selection",
      "Artwork & Accessory",
      "Services Lighting / Ceiling Design",
      "Consultation Material",
      "Finish Selections Space",
      "Planning Sustainable Design",
      "Theme & Concept Development",
      "Custom Cabinetry Design",
      "Adaptive Re-use",
    ],
  },
  {
    subType: "furniture-manufacturing",
    id: uuid(),
    itemType: "service-item",
    orderIdx: 2,
    timestamp: Date.now(),
    pk: {
      itemType: "service-item",
      orderIdx: 2,
    },
    images: {
      [uuid()]: {
        pk: {
          itemType: "service-item",
          orderIdx: 0,
        },
        id: uuid(),
        timestamp: Date.now(),
        imgUrl: "",
        placeholderUrl: "",
        description: "",
        orderIdx: 0,
      },
    },
    subCategories: [
      "Custom Furniture Design",
      "Textile Technology",
      "Furniture Selection",
      "Wall Panelling Design",
      "Mirror Design ",
      "Custom Cabinetry Manufacturing",
      "Custom Outdoor Furniture",
      "Custom Baby & Child",
      "Furniture Plans & Detailed Specifications",
      "DevelopmentFF&E Inventories",
      "Re-Use AnalysisFF&E",
    ],
  },
  {
    subType: "client-visualization",
    id: uuid(),
    itemType: "service-item",
    orderIdx: 3,
    timestamp: Date.now(),
    pk: {
      itemType: "service-item",
      orderIdx: 3,
    },
    images: {
      [uuid()]: {
        pk: {
          itemType: "service-item",
          orderIdx: 0,
        },
        id: uuid(),
        timestamp: Date.now(),
        imgUrl: "",
        placeholderUrl: "",
        description: "",
        orderIdx: 0,
      },
    },
    subCategories: [
      "Animations & Renderings",
      "3D Architectural Modeling",
      "Photo-Real / Non-Photo-Real Renderings",
      "3D Animations",
      "360 Degree VR Tours",
      "Coordination Design",
      "Analysis Material & Finish",
      "Mood Boards",
    ],
  },
];
